pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r FenicsATLdocs/public/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'