site_name: FenicsATL documentation

nav:
    - Home: index.md
    - Get started : getstarted.md
    - User guide : userguide.md
    - VS code @LPC : VisualCodeAtLPC.md
    - FenStruct : FenStruct.md
    - FenLoad : FenLoad.md
    - FenGraphs : FenGraphs.md
    - FenUtils : FenUtils.md
    - About: about.md
theme:
  name: readthedocs
  logo : assets/FENICS_white_logo.png

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.bokeh.org/bokeh/release/bokeh-2.3.3.min.js
  - https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.3.min.js

extra_css: [css/extra.css]

markdown_extensions:
    - toc:
        permalink: 
    - mdx_math
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.critic
    - pymdownx.mark
    - pymdownx.snippets
